version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.8
    commands:
      - npm i npm@latest -g
      - npm install -g serverless@latest
      - npm install serverless-python-requirements
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Deploying infra
      - (cd infrastructure && serverless deploy -v --force --env=prd)
      - echo vue
      - cd vue-project
      - npm install
  build:
    commands:
      - echo Build Phase
      - ls
      - echo ls build phase
      - npm run build
      - ls
  post_build:
    commands:
      - echo PostBuild Phase
      - ls
      - aws s3 sync ./dist s3://botentry
      - aws s3api put-bucket-acl --bucket botentry --acl public-read
      - echo Finished
